#! /usr/bin/env python
import rospy
import actionlib

from move_base_msgs.msg import MoveBaseGoal

if __name__ == '__main__':
    rospy.init_node('test_move_base')
    client = actionlib.SimpleActionClient('move_base', MoveBaseGoal)
    client.wait_for_server()

    goal = MoveBaseGoal()
    goal.target_pose.pose.position.x = 2
    goal.target_pose.pose.position.y = 2
    goal.target_pose.header.frame_id = "map"

    client.send_goal(goal)
    client.wait_for_result(rospy.Duration.from_sec(30.0))
    result = client.get_result()
    rospy.loginfo("{}".format(result))